# Introduction to Tensors

In [3]:
import tensorflow as tf
import numpy as np

- Tensors are multidimensional arrays with a uniform type
- All tensors are immuntable

## Basics

In [13]:
# Scalar or Rank-0 Tensor: value without axis
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [15]:
# Vector or Rank-1 Tensor: vector has one axis
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [17]:
# Matrix or Rank-2 Tensor: Matrix has two axises
rank_2_tensor =tf.constant([[1,0,0], [0,1,0], [0,0,1]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float16)


In [23]:
print("a scalar tensor has Shape : {}".format(rank_0_tensor.shape))
print("a Vector tensor has Shape : {}".format(rank_1_tensor.shape))
print("a Matrix tensor has Shape : {}".format(rank_2_tensor.shape))

a scalar tensor has Shape : ()
a Vector tensor has Shape : (3,)
a Matrix tensor has Shape : (3, 3)


In [24]:
# Tensor with rank > 2
rank_3_tensor = tf.constant([[[1,2,3], [4,2,5]],[[3,4,2],[5,1,7]]])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3]
  [4 2 5]]

 [[3 4 2]
  [5 1 7]]], shape=(2, 2, 3), dtype=int32)


In [25]:
print("a Rank-3 tensor has Shape : {}".format(rank_3_tensor.shape))

a Rank-3 tensor has Shape : (2, 2, 3)


- Converting a Tensor to a numpy array

In [26]:
# using numpy.array()
np.array(rank_3_tensor)

array([[[1, 2, 3],
        [4, 2, 5]],

       [[3, 4, 2],
        [5, 1, 7]]], dtype=int32)

In [28]:
# using tf.Tensor.numpy()
rank_2_tensor.numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float16)

- Tensors often are of common dtypes like float and int, but they could also contains other types like:
    - complex
    - string

In [62]:
rank_1_complex_tensor = tf.complex(tf.random.uniform(minval=-5, maxval=5, shape=[3]), tf.random.uniform(minval=-5, maxval=5, shape=[3]))

The base `tf.Tensor clas`s requires tensors to be "rectangular"---that is, along each axis, every element is the same size. However, there are specialized types of tensors that can handle different shapes:

- Ragged tensors (see RaggedTensor)
- Sparse tensors (see SparseTensor)

## Basic Math Operations 

In [63]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

In [64]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [65]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [66]:
a-b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [69]:
# element wise multiplication!
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [70]:
# **MATRIX MULTIPLICATION**
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [73]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [75]:
tf.matmul(b, a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [4, 6]], dtype=int32)>

In [76]:
b@a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [4, 6]], dtype=int32)>

In [77]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



## Operations using Tensors 

In [81]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# find largest value
print(tf.reduce_max(c))

# sum all the elements
print(tf.reduce_sum(c))

# take the mean over all the elements in the tensor
print(tf.reduce_mean(c))

#find the index of the largest value in the tensor
print(tf.math.argmax(c))

# compute the softmax
print(tf.nn.softmax(c, axis=0))




tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[0.00247262 0.98201376]
 [0.9975274  0.01798621]], shape=(2, 2), dtype=float32)


## Shapes of Tensors

- __Shape__ the length of each of the axis of the tensor
- __Rank__ the number of axises in the tensor
- __Axis/Dimension__ a particular dimension of the tensor
- __Size__ the total number of elements in the tensor

In [85]:
rank_4_tensor = tf.zeros([2,2,3,5])

In [86]:
rank_4_tensor.shape

TensorShape([2, 2, 3, 5])

- `TensorShape` object gives access to these shape properties of tensors

In [95]:
print("Data type of all elements : {}".format(rank_4_tensor.dtype))
print("Number of axis/Rank : {}".format(rank_4_tensor.ndim)) #ndim returns int
print("Size of tensor : {}".format(tf.size(rank_4_tensor).numpy()))
print("Number of Elements in the first axis {}".format(rank_4_tensor.shape[0]))
print("Number of Elements in the LAST axis {}".format(rank_4_tensor.shape[-1]))

Data type of all elements : <dtype: 'float32'>
Number of axis/Rank : 4
Rank of Tensor: 4
Size of tensor : 60
Number of Elements in the first axis 2
Number of Elements in the LAST axis 5


- note that the Tensor.ndim and Tensor.shape attributes don't return Tensor objects. If you need a Tensor use the tf.rank or tf.shape function. This difference is subtle, but it can be important when building graphs (later).

In [100]:
print(type(rank_4_tensor.ndim))
print(type(tf.rank(rank_4_tensor)), '\n')

print(type(rank_4_tensor.shape))
print(type(tf.shape(rank_4_tensor)))

<class 'int'>
<class 'tensorflow.python.framework.ops.EagerTensor'> 

<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


- While axes are often referred to by their indices, you should always keep track of the meaning of each. 
- Often axes are ordered from *global to local*: 
    - The batch axis first, 
    - followed by spatial dimensions, and 
    - features for each location last. 
- This way feature vectors are contiguous regions of memory

- Here is the meanings of four axises of a rank 4 tensor
1. axis 0 -> Batch
2. axis 1 -> Height 
3. axis 2 -> Width
4. axis 3 -> Features

- Base `tf.Tensor` requires that the tensor be __rectangular__ ie along each axis every element is the same size
- However, specialized types of Tensor classes are able to handle differenet Shapes
    - Ragged tensors (see [RaggedTensor](https://www.tensorflow.org/guide/tensor#ragged_tensors) below)
    - Sparse tensors (see [SparseTensor](https://www.tensorflow.org/guide/tensor#sparse_tensors) below)

## Indexing 

### Single Axis Indexing

Rules of Indexing
- Index starts at 0
- negative index counts backward
- `:` is used for slicing `start:stop:step`


In [101]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


- Indexing with a scalar removes the axis:

In [109]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


- Indexing with a : slice keeps the axis:

In [112]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


### Multi Axis Indexing

In [125]:
print(rank_2_tensor.numpy())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [126]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

1.0


In [127]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [0. 1. 0.]
Second column: [0. 1. 0.]
Last row: [0. 0. 1.]
First item in last column: 0.0
Skip the first row:
[[0. 1. 0.]
 [0. 0. 1.]] 



## Manipulating Shapes

## Sptring

In [141]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [142]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [144]:
#If you pass unicode characters they are utf-8 encoded.

tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

In [145]:
# You can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))
# ...but it turns into a `RaggedTensor` if you split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [137]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [138]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [140]:
# Or split it up as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


## Sparse Tensors

- ` tf.SparseTensor`

In [146]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
