# Modules, Layers, and models 

In [2]:
import tensorflow as tf

- `tf.Module` class manages `tf.Variable` objects and their values as well as the `tf.function` objects that operates over them.
- this classes enables exporting of the the values of the Variable (using `tf.train.Checkpoint`) and the graph

- save and restore the values of your variables using `tf.train.Checkpoint`. This is useful during training as it is quick to save and restore a model's state.
- import and export the `tf.Variable` values and the `tf.function` graphs using `tf.saved_model`. This allows you to run your model independently of the Python program that created it.

In [3]:
class MyModule(tf.Module):
    def __init__(self, value):
        self.weight = tf.Variable(value)
    
    @tf.function
    def multiply(self, x):
        return x*self.weight
    

In [12]:
mod = MyModule([[1,2,3],[1,2,3]])
mod.multiply(tf.constant(2))

2023-07-08 18:47:11.230243: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [2, 4, 6]], dtype=int32)>

In [13]:
save_path = './other_files/module_0'
tf.saved_model.save(mod, save_path)

INFO:tensorflow:Assets written to: ./other_files/assets


In [14]:
saved_path = './other_files/module_0'

reloaded_mod = tf.saved_model.load(saved_path)

In [16]:
reloaded_mod.multiply(2)

2023-07-08 18:57:58.642187: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [2, 4, 6]], dtype=int32)>

- The `tf.keras.layers.Layer` and `tf.keras.Model` classes build on `tf.Module` providing additional functionality and convenience methods for building, training, and saving models.