# Basic Concepts of Tensorflow

In [2]:
import tensorflow as tf
import numpy as np

## Tensors

- Tensorflow deals with multidimenstional arrays or Tensors represented as `tf.Tensor`
- here `x` is a 2-d Tensor

In [41]:
x = tf.constant(np.random.normal(1,1,6).reshape(2,3))

- `shape` of a `Tensor` tells the size of the Tensor along each axis

In [47]:
print(x.shape)

(2, 3)


- `dtype` tells the type of all the elements in the Tensor

In [49]:
print(x.dtype)

<dtype: 'float64'>


### Standard Mathematical operations works with tensors in tf

- addition

In [53]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[2.21184183, 3.85308796, 0.58187833],
       [3.89778944, 2.12421164, 1.44872504]])>

In [54]:
5*x

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[5.52960459, 9.63271991, 1.45469582],
       [9.74447361, 5.31052911, 3.62181259]])>

- vector transpose

In [64]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1.10592092, 1.94889472],
       [1.92654398, 1.06210582],
       [0.29093916, 0.72436252]])>

- dot product of two matrices: in this case
    - dot product of x and xT

In [62]:
x@tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.01927839, 4.41226244],
       [4.41226244, 5.45096047]])>

In [61]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1.10592092, 1.94889472],
       [1.92654398, 1.06210582],
       [0.29093916, 0.72436252]])>

- dot product of 2x2 matrix with itself

In [70]:
y = tf.constant([[1,2],[1,2]])

In [72]:
y@y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 6],
       [3, 6]], dtype=int32)>

- concatination of two or more tensors

In [79]:
tf.concat([y,y], axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [1, 2, 1, 2]], dtype=int32)>

In [80]:
tf.concat([y,y], axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]], dtype=int32)>

- Softmax function operation

In [87]:
tf.nn.softmax(x, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.26921072, 0.61162386, 0.11916543],
       [0.58621056, 0.24150499, 0.17228444]])>

In [89]:
tf.nn.softmax(x, axis=0)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.30090884, 0.70358708, 0.39330916],
       [0.69909116, 0.29641292, 0.60669084]])>

In [90]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.26921072, 0.61162386, 0.11916543],
       [0.58621056, 0.24150499, 0.17228444]])>

- reduce sum of a matrix

In [91]:
tf.reduce_sum(y)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [92]:
tf.reduce_sum(tf.nn.softmax(x, axis=-1))

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [95]:
tf.reduce_sum(tf.nn.softmax(x, axis=0)) # the reduce sum of the matrix here is 3 because there are three columns and the axis softmax is applied to is 0

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [94]:
tf.reduce_sum(tf.nn.softmax(x, axis=1))

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

## Check if tensorflow is using hardware accelarator

In [102]:
if tf.config.list_physical_devices('GPU'):
    print('Tensorflow **IS** using GPU')
else:
    print('Tensorflow **IS NOT** using GPU')

Tensorflow **IS** using GPU


## Variables

- Tensorflow `Tensor` is **immutable**
- in order to store variable matrices of, say,  _weights_ for a neural network then `tf.Variable` is suitable

In [104]:
var = tf.Variable([0.0, 0.0, 0.0])

In [105]:
var.assign([1,2,3])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [106]:
var.assign_add([1,1,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [108]:
print(var.shape)

(3,)


In [109]:
print(var.dtype)

<dtype: 'float32'>


## Auto Differentiation

- `tf` implements _autodif_ to enable automatic calculation of gradients using calculus

In [139]:
# let's take scaler x
x = tf.Variable(1.0)

#define a function f(x) = y
def f(x):
    y = x**2 + 2*x - 5
    return y

In [140]:
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

- calculating dy/dx
- we know that the derivative, f'(x), of f(x) is f2x+2 
- tf calculate this function using autodif

In [142]:
with tf.GradientTape() as tape:
    y = f(x)

#let take f'(x) as g_x
g_x = tape.gradient(y,x) #g(x) = dy/dx
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

## Graphs and tf.function

In [143]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

In [144]:
x = tf.constant([1, 2, 3])
my_func(x)

Tracing.



2023-07-07 23:10:35.134016: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [145]:
x = tf.constant([10, 9, 8])
my_func(x)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

- Notice how the second time `my_func` is run the nontensorflow part of the function is not run
- `Tracing.` is not printed as after the first run the `tf.function` declaration enables tensorflow to build an optimization graph
- this optimization graph can be exported to be used on servers as well as mobile devices using `tf.saved_model`